version: '3.9'

services:
  tasktracker:
    image: ghcr.io/rafailowitsch/tasktracker/tasktracker:latest
    command: ./wait-for-postgres.sh db ./tasktracker
    ports:
      - 8082:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
    build: ./

  db:
    restart: always
    image: postgres:16.1
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=tasktracker
    ports:
      - 5441:5432