env: "local"

postgres:
  host:     localhost
  port:     5434
  dbname:   tasktracker
  username: postgres
  password: qwerty

http:
  host:         localhost
  port:         8008
  timeout:      4s
  idle_timeout: 60s

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h