env: "prod"

postgres:
  host:     db
  port:     5432
  dbname:   tasktracker
  username: postgres
  password: qwerty

http:
  host:         0.0.0.0
  port:         8080
  timeout:      4s
  idle_timeout: 60s

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h